Remove unused define in header
This comment causes compiler errors on some platforms.

    src/seatest.h:79:1: error: expected identifier or ‘(’ before ‘/’ token
     //#define run_test(test) do { if(seatest_should_run(__FILE__, #test)) {seatest_suite_setup(); seatest_setup(); test(); seatest_teardown(); seatest_suite_teardown(); seatest_run_test(__FILE__, #test);  }} while (0)
      ^
      src/seatest.h:79:3: error: stray ‘#’ in program

with this change make will complete successfully on unix platforms.